name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: CMake Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests (Posix)
        if: (startsWith(matrix.os, 'ubuntu')) || (startsWith(matrix.os, 'macos'))
        run: cd tests && ./run_tests.sh

      - name: Run tests (Windows)
        if: startsWith(matrix.os, 'windows')
        run: cd tests && ./run_tests.ps1
